

const DefaultPreset = {
    identifier: "#0f172a",
    light: {
        "background": "#ffffff",
        "foreground": "#0f172a",
        "muted": "#f1f5f9",
        "mutedForeground": "#64748b",
        "popover": "#ffffff",
        "popoverForeground": "#0f172a",
        "border": "#e2e8f0",
        "input": "#e2e8f0",
        "card": "#ffffff",
        "cardForeground": "#0f172a",
        "primary": "#0f172a",
        "primaryForeground": "#f8fafc",
        "secondary": "#f1f5f9",
        "secondaryForeground": "#0f172a",
        "accent": "#f1f5f9",
        "accentForeground": "#0f172a",
        "destructive": "#ff0000",
        "destructiveForeground": "#f8fafc",
        "ring": "#94a3b8",
        "radius": "0.5rem"
    },
    dark:{
        "background": "#030711",
        "foreground": "#e1e7ef",
        "muted": "#0f1629",
        "mutedForeground": "#7f8ea3",
        "popover": "#030711",
        "popoverForeground": "#94a3b8",
        "border": "#1d283a",
        "input": "#1d283a",
        "card": "#030711",
        "cardForeground": "#e1e7ef",
        "primary": "#f8fafc",
        "primaryForeground": "#020205",
        "secondary": "#0f172a",
        "secondaryForeground": "#f8fafc",
        "accent": "#1d283a",
        "accentForeground": "#f8fafc",
        "destructive": "#811d1d",
        "destructiveForeground": "#f8fafc",
        "ring": "#1d283a",
        "radius": "0.5rem"
    }
 } 

const Cyberpunk = {
        identifier: "#FCEE09",
        light: {
            "background": "#f7f7f7",
            "foreground": "#ff003c",
            "muted": "#fcf300",
            "mutedForeground": "#00f0ff",
            "popover": "#ffffff",
            "popoverForeground": "#0f172a",
            "border": "#ff003c",
            "input": "#e2e8f0",
            "card": "#ffffff",
            "cardForeground": "#0f172a",
            "primary": "#fcf300",
            "primaryForeground": "#ff003c",
            "secondary": "#f1f5f9",
            "secondaryForeground": "#0f172a",
            "accent": "#fcf300",
            "accentForeground": "#0f172a",
            "destructive": "#ff0000",
            "destructiveForeground": "#f8fafc",
            "ring": "#94a3b8",
            "radius": "0.5rem"
        },
dark:{
    "background": "#050B1A",
    "foreground": "#05dae8",
    "muted": "#0f1629",
    "mutedForeground": "#fdf400",
    "popover": "#030711",
    "popoverForeground": "#94a3b8",
    "border": "#700000",
    "input": "#1d283a",
    "card": "#000228",
    "cardForeground": "#e1e7ef",
    "primary": "#fcee09",
    "primaryForeground": "#020205",
    "secondary": "#0f172a",
    "secondaryForeground": "#f8fafc",
    "accent": "#1d283a",
    "accentForeground": "#f8fafc",
    "destructive": "#ff003c",
    "destructiveForeground": "#fcee09",
    "ring": "#1d283a",
    "radius": "0.5rem"
}
 }

const BOTW = {
    identifier: "#2B8091",
    light: {
        "background": "#f7f4e6",
        "foreground": "#0f172a",
        "muted": "#f1f5f9",
        "mutedForeground": "#b9a163",
        "popover": "#ffffff",
        "popoverForeground": "#0f172a",
        "border": "#005f69",
        "input": "#e2e8f0",
        "card": "#ffffff",
        "cardForeground": "#0f172a",
        "primary": "#43b089",
        "primaryForeground": "#f8fafc",
        "secondary": "#f1f5f9",
        "secondaryForeground": "#0f172a",
        "accent": "#f1f5f9",
        "accentForeground": "#0f172a",
        "destructive": "#ff0000",
        "destructiveForeground": "#f8fafc",
        "ring": "#94a3b8",
        "radius": "0.5rem"
    },
    dark:{
        "background": "#05112e",
        "foreground": "#8bd8ef",
        "muted": "#f5faff",
        "mutedForeground": "#b5f956",
        "popover": "#07191c",
        "popoverForeground": "#40b29f",
        "border": "#fef0cb",
        "input": "#89e7d0",
        "card": "#07191c",
        "cardForeground": "#40b29f",
        "primary": "#2c7fc9",
        "primaryForeground": "#07191c",
        "secondary": "#f5faff",
        "secondaryForeground": "#40b29f",
        "accent": "#f5faff",
        "accentForeground": "#40b29f",
        "destructive": "#811d1d",
        "destructiveForeground": "#f8fafc",
        "ring": "#89e7d0",
        "radius": "0.5rem"
    }
}

const Witcher = {
    identifier: "#b50c0f",
    light: {
        "background": "#eaeaea",
        "foreground": "#310a0b",
        "muted": "#ffffff",
        "mutedForeground": "#b50d0d",
        "popover": "#eaeaea",
        "popoverForeground": "#b50c0f",
        "border": "#272727",
        "input": "#e2e8f0",
        "card": "#eaeaea",
        "cardForeground": "#b50c0f",
        "primary": "#b50c0f",
        "primaryForeground": "#eaeaea",
        "secondary": "#310a0b",
        "secondaryForeground": "#fbf9f9",
        "accent": "#fafafa",
        "accentForeground": "#b50c0f",
        "destructive": "#ff0000",
        "destructiveForeground": "#f8fafc",
        "ring": "#94a3b8",
        "radius": "0.5rem"
    },
    dark:{
        "background": "#041725",
        "foreground": "#eaeaea",
        "muted": "#4e636c",
        "mutedForeground": "#b50c0f",
        "popover": "#041725",
        "popoverForeground": "#b50c0f",
        "border": "#272727",
        "input": "#272727",
        "card": "#052035",
        "cardForeground": "#b50c0f",
        "primary": "#b50c0f",
        "primaryForeground": "#041725",
        "secondary": "#eaeaea",
        "secondaryForeground": "#b50c0f",
        "accent": "#4e636c",
        "accentForeground": "#b50c0f",
        "destructive": "#811d1d",
        "destructiveForeground": "#f8fafc",
        "ring": "#0c76ac",
        "radius": "0.5rem"
    }
}

const EldenRing = {
    identifier: "#DEB85D",
    light:{
        "background": "#f7f3d9",
        "foreground": "#071635",
        "muted": "#d9b959",
        "mutedForeground": "#f2d16c",
        "popover": "#f7f3d9",
        "popoverForeground": "#071635",
        "border": "#30413d",
        "input": "#2f402d",
        "card": "#f7f3d9",
        "cardForeground": "#071635",
        "primary": "#d9b959",
        "primaryForeground": "#f7f3d9",
        "secondary": "#3c5473",
        "secondaryForeground": "#071635",
        "accent": "#2f402d",
        "accentForeground": "#071635",
        "destructive": "#ff0000",
        "destructiveForeground": "#f8fafc",
        "ring": "#2f402d",
        "radius": "0.5rem"
    },
    dark:{
        "background": "#000408",
        "foreground": "#dad2b0",
        "muted": "#30413d",
        "mutedForeground": "#deb85d",
        "popover": "#000408",
        "popoverForeground": "#deb85d",
        "border": "#adaae7",
        "input": "#242650",
        "card": "#000408",
        "cardForeground": "#deb85d",
        "primary": "#deb85d",
        "primaryForeground": "#000408",
        "secondary": "#30413d",
        "secondaryForeground": "#deb85d",
        "accent": "#30413d",
        "accentForeground": "#deb85d",
        "destructive": "#731701",
        "destructiveForeground": "#f8fafc",
        "ring": "#242650",
        "radius": "0.5rem"
    }
}

const Skyrim ={
    identifier: "#deeff9",
    light:{
        "background": "#d0dedf",
        "foreground": "#071635",
        "muted": "#dcc897",
        "mutedForeground": "#4f7532",
        "popover": "#f7f3d9",
        "popoverForeground": "#071635",
        "border": "#30413d",
        "input": "#2f402d",
        "card": "#829cab",
        "cardForeground": "#071635",
        "primary": "#deeff9",
        "primaryForeground": "#000000",
        "secondary": "#3c5473",
        "secondaryForeground": "#071635",
        "accent": "#2f402d",
        "accentForeground": "#071635",
        "destructive": "#ff0000",
        "destructiveForeground": "#f8fafc",
        "ring": "#2f402d",
        "radius": "0.5rem"
    },
    dark:{
        "background": "#111b24",
        "foreground": "#d0dedf",
        "muted": "#514f4c",
        "mutedForeground": "#869eaa",
        "popover": "#111b24",
        "popoverForeground": "#d0dedf",
        "border": "#263435",
        "input": "#4d4133",
        "card": "#111b24",
        "cardForeground": "#d0dedf",
        "primary": "#d0dedf",
        "primaryForeground": "#111b24",
        "secondary": "#2b3c43",
        "secondaryForeground": "#d0dedf",
        "accent": "#2b3c43",
        "accentForeground": "#d0dedf",
        "destructive": "#731701",
        "destructiveForeground": "#f8fafc",
        "ring": "#4d4133",
        "radius": "0.5rem"
    }
}

const BauldersGate = {
    identifier: "#F0740F",
    light:{
        "background": "#f7f7f7",
        "foreground": "#153c61",
        "muted": "#688eac",
        "mutedForeground": "#2a7817",
        "popover": "#f7f7f7",
        "popoverForeground": "#24431c",
        "border": "#b19682",
        "input": "#b19682",
        "card": "#f7f7f7",
        "cardForeground": "#24431c",
        "primary": "#2f8b18",
        "primaryForeground": "#f7f7f7",
        "secondary": "#688eac",
        "secondaryForeground": "#fafafa",
        "accent": "#688eac",
        "accentForeground": "#24431c",
        "destructive": "#ff0000",
        "destructiveForeground": "#f8fafc",
        "ring": "#b19682",
        "radius": "0.5rem"
    },
    dark:{
        "background": "#000000",
        "foreground": "#ecc8a7",
        "muted": "#801e1e",
        "mutedForeground": "#85b8cf",
        "popover": "#000000",
        "popoverForeground": "#66142d",
        "border": "#071f31",
        "input": "#f7772c",
        "card": "#000000",
        "cardForeground": "#66142d",
        "primary": "#ac2a37",
        "primaryForeground": "#000000",
        "secondary": "#e3ba88",
        "secondaryForeground": "#66142d",
        "accent": "#e3ba88",
        "accentForeground": "#66142d",
        "destructive": "#731701",
        "destructiveForeground": "#f8fafc",
        "ring": "#f7772c",
        "radius": "0.5rem"
    }
}

const Minecraft = {
    identifier :"#2f8b18",
    light:{
        "background": "#ebffdb",
        "foreground": "#204601",
        "muted": "#854f2b",
        "mutedForeground": "#51ad00",
        "popover": "#e6ffd1",
        "popoverForeground": "#24431c",
        "border": "#b19682",
        "input": "#b19682",
        "card": "#e6ffd1",
        "cardForeground": "#24431c",
        "primary": "#2f8b18",
        "primaryForeground": "#e6ffd1",
        "secondary": "#854f2b",
        "secondaryForeground": "#fafafa",
        "accent": "#854f2b",
        "accentForeground": "#24431c",
        "destructive": "#ff0000",
        "destructiveForeground": "#f8fafc",
        "ring": "#b19682",
        "radius": "0.5rem"
    },
    dark:{
        "background": "#0c1702",
        "foreground": "#dbfebe",
        "muted": "#854f2b",
        "mutedForeground": "#477a1e",
        "popover": "#0c1702",
        "popoverForeground": "#477a1e",
        "border": "#61371f",
        "input": "#61371f",
        "card": "#0c1702",
        "cardForeground": "#477a1e",
        "primary": "#70b237",
        "primaryForeground": "#0c1702",
        "secondary": "#854f2b",
        "secondaryForeground": "#477a1e",
        "accent": "#854f2b",
        "accentForeground": "#477a1e",
        "destructive": "#731701",
        "destructiveForeground": "#f8fafc",
        "ring": "#61371f",
        "radius": "0.5rem"
    }

}

const Arcane ={
    identifier : "#611977",
    light:{
        "background": "#eeeff1",
        "foreground": "#5f1a75",
        "muted": "#f7f7f7",
        "mutedForeground": "#fa00cc",
        "popover": "#eeeff1",
        "popoverForeground": "#1c6a6e",
        "border": "#93B94B",
        "input": "#ff06b9",
        "card": "#eeeff1",
        "cardForeground": "#1c6a6e",
        "primary": "#581d71",
        "primaryForeground": "#eeeff1",
        "secondary": "#123b21",
        "secondaryForeground": "#ffffff",
        "accent": "#0284e1",
        "accentForeground": "#1c6a6e",
        "destructive": "#731701",
        "destructiveForeground": "#f8fafc",
        "ring": "#ff06b9",
        "radius": "0.5rem"
    },
    dark:{
        "background": "#100e0f",
        "foreground": "#ffffff",
        "muted": "#15301f",
        "mutedForeground": "#ff09d1",
        "popover": "#100e0f",
        "popoverForeground": "#611977",
        "border": "#3bd0fd",
        "input": "#3bd0fd",
        "card": "#100e0f",
        "cardForeground": "#611977",
        "primary": "#611977",
        "primaryForeground": "#ffffff",
        "secondary": "#69cc69",
        "secondaryForeground": "#611977",
        "accent": "#69cc69",
        "accentForeground": "#611977",
        "destructive": "#ff0000",
        "destructiveForeground": "#f8fafc",
        "ring": "#3bd0fd",
        "radius": "0.5rem"
    }
}
const Frieren = {
    identifier:"#8d488e",
    light:{
        "background": "#e8e6f0",
        "foreground": "#000000",
        "muted": "#9b3422",
        "mutedForeground": "#a538ad",
        "popover": "#e8e6f0",
        "popoverForeground": "#8d488e",
        "border": "#ffffff",
        "input": "#ffffff",
        "card": "#e8e6f0",
        "cardForeground": "#8d488e",
        "primary": "#8d488e",
        "primaryForeground": "#e8e6f0",
        "secondary": "#9b3422",
        "secondaryForeground": "#8d488e",
        "accent": "#fcfbf9",
        "accentForeground": "#ffffff",
        "destructive": "#731701",
        "destructiveForeground": "#f8fafc",
        "ring": "#ffffff",
        "radius": "0.5rem"
    },
    dark:{
        "background": "#11151d",
        "foreground": "#cec6dc",
        "muted": "#5c325d",
        "mutedForeground": "#804790",
        "popover": "#11151d",
        "popoverForeground": "#eae4f0",
        "border": "#fcfbf9",
        "input": "#fcfbf9",
        "card": "#11151d",
        "cardForeground": "#eae4f0",
        "primary": "#eae4f0",
        "primaryForeground": "#11151d",
        "secondary": "#5c325d",
        "secondaryForeground": "#eae4f0",
        "accent": "#5c325d",
        "accentForeground": "#eae4f0",
        "destructive": "#a84033",
        "destructiveForeground": "#f8fafc",
        "ring": "#fcfbf9",
        "radius": "0.5rem"
    }
}
export const Presets = {
    "Default" : DefaultPreset,
    "Cyberpunk": Cyberpunk,
    "Rise, Tarnished" : EldenRing,
    "Beyond Journey's End": Frieren,
    "The Wild Hunt": Witcher,
    "Dynasties and Dystopia": Arcane,
    "Breath of the Wild": BOTW,
    "Raphael's Final Act": BauldersGate,
    "You're Finally Awake": Skyrim,
    "Creeper": Minecraft,
  }

export  const presetMapping = {
    0: "Default",
    1: "Cyberpunk",
    2: "Rise, Tarnished",
    3: "Beyond Journey's End",
    4: "The Wild Hunt",
    5: "Dynasties and Dystopia",
    6: "Breath of the Wild",
    7: "Raphael's Final Act",
    8: "You're Finally Awake",
    9: "Creeper",
  }



export const PrimaryColors = {
    fields: [
      "primary",
      "cardForeground",
      "secondaryForeground",
      "accentForeground",
      "foreground",
      "mutedForeground",
      "popoverForeground",
    ],
    values: [
      { name: "Default Dark", value: "#f8fafc" },
      { name: "Default Light", value: "#0f172a" },
      { name: "Teal", value: "#007f80" },
      { name: "Red", value: "#FF0000" },
      { name: "Green", value: "#00FF00" },
      { name: "Blue", value: "#0000FF" },
      { name: "Yellow", value: "#FFFF00" },
      { name: "Cyan", value: "#00FFFF" },
      { name: "Magenta", value: "#FF00FF" },
    ],
  }

export const SecondaryColors = {
    fields: ["secondary", "muted", "accent"],
    values: [
      { name: "Default Dark", value: "#0f172a" },
      { name: "Default Light", value: "#f1f5f9" },
      { name: "Sky", value: "#7CE2FE" },
      { name: "Amber", value: "#FFE7B3" },
      { name: "Dull Teal", value: "#0D2D2A" },
      { name: "Dull Iris", value: "#202248" },
    ],
  }

export const BackgroundColors = {
    fields: ["background", "popover", "card", "primaryForeground"],
    values: [
      { name: "Default Dark", value: "#030711" },
      { name: "Default Light", value: "#ffffff" },

      { name: "Gold", value: "#ffd900" },
      { name: "Lavender", value: "#E6E6FA" },
      { name: "Indigo", value: "#4B0082" },
      { name: "Salmon", value: "#FA8072" },
      { name: "Beige", value: "#F5F5DC" },
      { name: "Wheat", value: "#F5DEB3" },
      { name: "Ivory", value: "#FFFFF0" },
    ],
  }
export const BorderColors = {
    fields: ["border", "ring", "input"],
    values: [
      { name: "Default Dark", value: "#1d283a" },
      { name: "Default Light", value: "#e2e8f0" },
      { name: "Purple", value: "#8E4EC6" },
      { name: "Ruby", value: "#E54666" },
      { name: "Jade", value: "#1FD8A4" },
    ],
  }
